### ISSUE TITLE
How can I remove the text: "DEMO"

### ISSUE THREAD

**Issue by hungk64it1x** [kredibel-id/VisionSample-Android#2]
Hi team,

I'm very impressive with your work, I have a question: If I want to modify the liveness layout, how can I remove the text "DEMO" always show in the camera's screen while doing face verification?

Thanks!

**Comment by hangga** [comment]
Hi @hungk64it1x 
Sorry, it's not possible right now.😊
Currently still in the development stage.
In the future, this product will be released as a paid service.😊

**Comment by hangga** [comment]
Hi @hungk64it1x do you mind if I close this issue?
